[package]
name = "bombadil"
version.workspace = true
edition.workspace = true

[lib]
name = "bombadil"
path = "src/lib.rs"

[dependencies]
antithesis_sdk = { workspace = true }
antithesis-fuzzer = { path = "../antithesis-fuzzer" }
anyhow = { workspace = true, features = ["backtrace"] }
boa_engine.workspace = true
bombadil-schema = { path = "../bombadil-schema" }
bombadil-ltl = { path = "../bombadil-ltl" }
hotpath.workspace = true
include_dir.workspace = true
log.workspace = true
oneshot = { version = "0.2.1", features = ["std"] }
oxc.workspace = true
oxc_resolver.workspace = true
oxc_str.workspace = true
oxc_traverse.workspace = true
owo-colors = { workspace = true, features = ["supports-colors"] }
num-traits.workspace = true
rand.workspace = true
rand_distr.workspace = true
rand_regex.workspace = true
regex.workspace = true
regex-syntax.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json.workspace = true
supports-color.workspace = true
tempfile.workspace = true
url = { workspace = true, features = ["serde"] }
willow-tree = { path = "../willow-tree" }

[dev-dependencies]
indoc.workspace = true
insta.workspace = true
hegeltest.workspace = true
